package store

import (
	"context"
	"encoding/json"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/jackc/pgx/v5/pgxpool"
)

//go:generate sqlc generate

// DB wraps the database connection pool and provides store methods
type DB struct {
	pool    *pgxpool.Pool
	queries Querier
}

// Querier interface for database operations (will be generated by sqlc)
type Querier interface {
	// User operations
	CreateUser(ctx context.Context, params CreateUserParams) (*User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (*User, error)
	GetUserByClerkID(ctx context.Context, clerkUserID string) (*User, error)
	GetUserByAPIKey(ctx context.Context, apiKey string) (*User, error)
	UpdateUserTier(ctx context.Context, params UpdateUserTierParams) (*User, error)
	UpdateUserAPIKey(ctx context.Context, params UpdateUserAPIKeyParams) (*User, error)
	DeleteUser(ctx context.Context, id uuid.UUID) error

	// Scan job operations
	CreateScanJob(ctx context.Context, params CreateScanJobParams) (*ScanJob, error)
	GetScanJobByID(ctx context.Context, id uuid.UUID) (*ScanJob, error)
	ListScanJobsByUser(ctx context.Context, params ListScanJobsParams) ([]ScanJob, error)
	CountScanJobsByUser(ctx context.Context, userID uuid.UUID) (int64, error)
	ListScanJobsByUserAndStatus(ctx context.Context, params ListScanJobsByStatusParams) ([]ScanJob, error)
	ListRecentScanJobsByUser(ctx context.Context, params ListRecentScansParams) ([]ScanJob, error)
	UpdateScanJobStatus(ctx context.Context, params UpdateScanJobStatusParams) (*ScanJob, error)
	UpdateScanJobStarted(ctx context.Context, id uuid.UUID) (*ScanJob, error)
	UpdateScanJobCompleted(ctx context.Context, params UpdateScanJobCompletedParams) (*ScanJob, error)
	UpdateScanJobFailed(ctx context.Context, id uuid.UUID) (*ScanJob, error)
	UpdateScanJobAuthConfirmed(ctx context.Context, params UpdateAuthParams) (*ScanJob, error)
	DeleteScanJob(ctx context.Context, id uuid.UUID) error

	// Finding operations
	CreateFinding(ctx context.Context, params CreateFindingParams) (*Finding, error)
	GetFindingByID(ctx context.Context, id uuid.UUID) (*Finding, error)
	ListFindingsByScanJob(ctx context.Context, params ListFindingsParams) ([]Finding, error)
	ListFindingsByScanJobAndSeverity(ctx context.Context, params ListFindingsBySeverityParams) ([]Finding, error)
	CountFindingsByScanJob(ctx context.Context, scanJobID uuid.UUID) (int64, error)
	CountFindingsBySeverity(ctx context.Context, scanJobID uuid.UUID) ([]SeverityCount, error)
	UpdateFinding(ctx context.Context, params UpdateFindingParams) (*Finding, error)
	DeleteFinding(ctx context.Context, id uuid.UUID) error

	// Report operations
	CreateReport(ctx context.Context, params CreateReportParams) (*Report, error)
	GetReportByID(ctx context.Context, id uuid.UUID) (*Report, error)
	GetReportByScanJobID(ctx context.Context, scanJobID uuid.UUID) (*Report, error)
	GetReportByShareToken(ctx context.Context, shareToken string) (*Report, error)
	ListReportsByUser(ctx context.Context, params ListReportsParams) ([]Report, error)
	UpdateReportShareToken(ctx context.Context, params UpdateShareParams) (*Report, error)
	RevokeReportShare(ctx context.Context, id uuid.UUID) (*Report, error)
	DeleteReport(ctx context.Context, id uuid.UUID) error

	// Dashboard analytics
	GetUserScanStats(ctx context.Context, userID uuid.UUID) (*UserScanStats, error)
	GetUserFindingStats(ctx context.Context, userID uuid.UUID) (*UserFindingStats, error)
	GetScansTrendOverTime(ctx context.Context, userID uuid.UUID) ([]ScanTrend, error)
	GetFindingsByCategoryStats(ctx context.Context, userID uuid.UUID) ([]CategoryStat, error)
	GetTopTargets(ctx context.Context, userID uuid.UUID, limit int32) ([]TopTarget, error)

	// Dashboard Phase 15
	GetScanStatistics(ctx context.Context, userID uuid.UUID) (*ScanStatistics, error)
	GetFindingsBySeverityStats(ctx context.Context, userID uuid.UUID) (*FindingSeverityStats, error)
	GetScanActivity(ctx context.Context, userID uuid.UUID, limit, offset int32) ([]ScanActivity, int64, error)
	GetVulnerabilityTrends(ctx context.Context, userID uuid.UUID, days int, startDate, endDate *time.Time) ([]VulnerabilityTrend, error)
	GetMostScannedTargets(ctx context.Context, userID uuid.UUID, limit int32) ([]TargetStats, int64, error)

	// History Phase 15
	GetScanHistory(ctx context.Context, filter HistoryFilter) ([]*ScanJobWithStats, int64, error)
	GetTargetScanHistory(ctx context.Context, userID uuid.UUID, target string, limit, offset int32) ([]*ScanJobWithStats, int64, error)

	// Diff Phase 15
	GetScanFindingsForDiff(ctx context.Context, scanJobID uuid.UUID) ([]*FindingForDiff, error)

	// Search
	SearchScans(ctx context.Context, params SearchParams) ([]ScanJob, error)
	SearchFindings(ctx context.Context, params SearchParams) ([]Finding, error)
}

// TxStore wraps database queries within a transaction
type TxStore struct {
	queries Querier
	tx      pgx.Tx
}

// NewDB creates a new database connection pool
func NewDB(connString string) (*DB, error) {
	// Configure connection pool
	config, err := pgxpool.ParseConfig(connString)
	if err != nil {
		return nil, fmt.Errorf("failed to parse connection string: %w", err)
	}

	// Set pool configuration
	config.MaxConns = 25
	config.MinConns = 5
	config.MaxConnLifetime = time.Hour
	config.MaxConnIdleTime = 30 * time.Minute
	config.HealthCheckPeriod = 5 * time.Minute

	// Create connection pool
	pool, err := pgxpool.NewWithConfig(context.Background(), config)
	if err != nil {
		return nil, fmt.Errorf("failed to create connection pool: %w", err)
	}

	// Verify connection
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	if err := pool.Ping(ctx); err != nil {
		pool.Close()
		return nil, fmt.Errorf("failed to ping database: %w", err)
	}

	return &DB{
		pool: pool,
	}, nil
}

// Close closes the database connection pool
func (d *DB) Close() {
	if d.pool != nil {
		d.pool.Close()
	}
}

// Ping checks database connectivity
func (d *DB) Ping(ctx context.Context) error {
	return d.pool.Ping(ctx)
}

// Pool returns the underlying connection pool
func (d *DB) Pool() *pgxpool.Pool {
	return d.pool
}

// BeginTx starts a new database transaction
func (d *DB) BeginTx(ctx context.Context) (*TxStore, error) {
	tx, err := d.pool.Begin(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to begin transaction: %w", err)
	}

	return &TxStore{
		tx: tx,
	}, nil
}

// Commit commits the transaction
func (tx *TxStore) Commit(ctx context.Context) error {
	return tx.tx.Commit(ctx)
}

// Rollback rolls back the transaction
func (tx *TxStore) Rollback(ctx context.Context) error {
	return tx.tx.Rollback(ctx)
}

// SetUserContext sets the RLS context for the current user
func (d *DB) SetUserContext(ctx context.Context, clerkUserID string, userUUID uuid.UUID) error {
	_, err := d.pool.Exec(ctx, "SELECT set_config('app.current_user_id', $1, true)", clerkUserID)
	if err != nil {
		return fmt.Errorf("failed to set user context: %w", err)
	}

	_, err = d.pool.Exec(ctx, "SELECT set_config('app.current_user_uuid', $1, true)", userUUID.String())
	if err != nil {
		return fmt.Errorf("failed to set user UUID context: %w", err)
	}

	return nil
}

// Exec executes a raw SQL query
func (d *DB) Exec(ctx context.Context, sql string, args ...interface{}) error {
	_, err := d.pool.Exec(ctx, sql, args...)
	return err
}

// QueryRow executes a raw SQL query and scans a single row
func (d *DB) QueryRow(ctx context.Context, sql string, args ...interface{}) pgx.Row {
	return d.pool.QueryRow(ctx, sql, args...)
}

// =============================================================================
// Domain Models
// =============================================================================

// User represents an application user
type User struct {
	ID          uuid.UUID `json:"id" db:"id"`
	ClerkUserID string    `json:"clerk_user_id" db:"clerk_user_id"`
	Tier        string    `json:"tier" db:"tier"`
	APIKey      string    `json:"api_key,omitempty" db:"api_key"`
	CreatedAt   time.Time `json:"created_at" db:"created_at"`
	UpdatedAt   time.Time `json:"updated_at" db:"updated_at"`
}

// ScanJob represents a security scan job
type ScanJob struct {
	ID              uuid.UUID       `json:"id" db:"id"`
	UserID          uuid.UUID       `json:"user_id" db:"user_id"`
	Target          string          `json:"target" db:"target"`
	TargetType      string          `json:"target_type" db:"target_type"`
	Scope           string          `json:"scope" db:"scope"`
	Status          string          `json:"status" db:"status"`
	AuthConfirmed   bool            `json:"auth_confirmed" db:"auth_confirmed"`
	AuthConfirmedIP string          `json:"auth_confirmed_ip,omitempty" db:"auth_confirmed_ip"`
	AuthConfirmedAt *time.Time      `json:"auth_confirmed_at,omitempty" db:"auth_confirmed_at"`
	CustomHeaders   json.RawMessage `json:"custom_headers,omitempty" db:"custom_headers"`
	StartedAt       *time.Time      `json:"started_at,omitempty" db:"started_at"`
	CompletedAt     *time.Time      `json:"completed_at,omitempty" db:"completed_at"`
	RiskScore       int32           `json:"risk_score,omitempty" db:"risk_score"`
	FindingCounts   json.RawMessage `json:"finding_counts,omitempty" db:"finding_counts"`
	CreatedAt       time.Time       `json:"created_at" db:"created_at"`
}

// Finding represents a security finding
type Finding struct {
	ID                uuid.UUID       `json:"id" db:"id"`
	ScanJobID         uuid.UUID       `json:"scan_job_id" db:"scan_job_id"`
	Module            string          `json:"module" db:"module"`
	Category          string          `json:"category" db:"category"`
	Severity          string          `json:"severity" db:"severity"`
	CVSSScore         float64         `json:"cvss_score,omitempty" db:"cvss_score"`
	CVSSVector        string          `json:"cvss_vector,omitempty" db:"cvss_vector"`
	OWASPStandard     string          `json:"owasp_standard,omitempty" db:"owasp_standard"`
	OWASPAgentic      string          `json:"owasp_agentic,omitempty" db:"owasp_agentic"`
	Title             string          `json:"title" db:"title"`
	Description       string          `json:"description" db:"description"`
	RawEvidence       string          `json:"raw_evidence,omitempty" db:"raw_evidence"`
	BusinessImpact    string          `json:"business_impact,omitempty" db:"business_impact"`
	Remediation       string          `json:"remediation,omitempty" db:"remediation"`
	RemediationEffort string          `json:"remediation_effort,omitempty" db:"remediation_effort"`
	References        json.RawMessage `json:"references,omitempty" db:"references"`
	CreatedAt         time.Time       `json:"created_at" db:"created_at"`
}

// Report represents a scan report
type Report struct {
	ID                 uuid.UUID       `json:"id" db:"id"`
	ScanJobID          uuid.UUID       `json:"scan_job_id" db:"scan_job_id"`
	PDFURL             string          `json:"pdf_url,omitempty" db:"pdf_url"`
	JSONURL            string          `json:"json_url,omitempty" db:"json_url"`
	ShareToken         string          `json:"share_token,omitempty" db:"share_token"`
	ShareExpiresAt     *time.Time      `json:"share_expires_at,omitempty" db:"share_expires_at"`
	ExecutiveSummary   string          `json:"executive_summary,omitempty" db:"executive_summary"`
	RemediationRoadmap json.RawMessage `json:"remediation_roadmap,omitempty" db:"remediation_roadmap"`
	CreatedAt          time.Time       `json:"created_at" db:"created_at"`
}

// =============================================================================
// Parameter Types
// =============================================================================

// CreateUserParams parameters for creating a user
type CreateUserParams struct {
	ClerkUserID string
	Tier        string
	APIKey      string
}

// UpdateUserTierParams parameters for updating user tier
type UpdateUserTierParams struct {
	ID   uuid.UUID
	Tier string
}

// UpdateUserAPIKeyParams parameters for updating user API key
type UpdateUserAPIKeyParams struct {
	ID     uuid.UUID
	APIKey string
}

// CreateScanJobParams parameters for creating a scan job
type CreateScanJobParams struct {
	UserID          uuid.UUID
	Target          string
	TargetType      string
	Scope           string
	Status          string
	AuthConfirmed   bool
	AuthConfirmedIP string
	CustomHeaders   json.RawMessage
	FindingCounts   json.RawMessage
}

// ListScanJobsParams parameters for listing scan jobs
type ListScanJobsParams struct {
	UserID uuid.UUID
	Limit  int32
	Offset int32
}

// ListScanJobsByStatusParams parameters for listing scan jobs by status
type ListScanJobsByStatusParams struct {
	UserID uuid.UUID
	Status string
	Limit  int32
	Offset int32
}

// ListRecentScansParams parameters for listing recent scans
type ListRecentScansParams struct {
	UserID uuid.UUID
	Limit  int32
}

// UpdateScanJobStatusParams parameters for updating scan status
type UpdateScanJobStatusParams struct {
	ID     uuid.UUID
	Status string
}

// UpdateScanJobCompletedParams parameters for completing a scan
type UpdateScanJobCompletedParams struct {
	ID            uuid.UUID
	RiskScore     int32
	FindingCounts json.RawMessage
}

// UpdateAuthParams parameters for confirming auth
type UpdateAuthParams struct {
	ID              uuid.UUID
	AuthConfirmedIP string
}

// CreateFindingParams parameters for creating a finding
type CreateFindingParams struct {
	ScanJobID         uuid.UUID
	Module            string
	Category          string
	Severity          string
	CVSSScore         float64
	CVSSVector        string
	OWASPStandard     string
	OWASPAgentic      string
	Title             string
	Description       string
	RawEvidence       string
	BusinessImpact    string
	Remediation       string
	RemediationEffort string
	References        json.RawMessage
}

// ListFindingsParams parameters for listing findings
type ListFindingsParams struct {
	ScanJobID uuid.UUID
	Limit     int32
	Offset    int32
}

// ListFindingsBySeverityParams parameters for listing findings by severity
type ListFindingsBySeverityParams struct {
	ScanJobID uuid.UUID
	Severity  string
	Limit     int32
	Offset    int32
}

// UpdateFindingParams parameters for updating a finding
type UpdateFindingParams struct {
	ID                uuid.UUID
	Severity          string
	CVSSScore         float64
	CVSSVector        string
	Title             string
	Description       string
	RawEvidence       string
	BusinessImpact    string
	Remediation       string
	RemediationEffort string
}

// CreateReportParams parameters for creating a report
type CreateReportParams struct {
	ScanJobID          uuid.UUID
	PDFURL             string
	JSONURL            string
	ShareToken         string
	ShareExpiresAt     *time.Time
	ExecutiveSummary   string
	RemediationRoadmap json.RawMessage
}

// ListReportsParams parameters for listing reports
type ListReportsParams struct {
	UserID uuid.UUID
	Limit  int32
	Offset int32
}

// UpdateShareParams parameters for updating report share
type UpdateShareParams struct {
	ID         uuid.UUID
	ShareToken string
	ExpiresAt  *time.Time
}

// SearchParams parameters for search queries
type SearchParams struct {
	UserID uuid.UUID
	Query  string
	Limit  int32
	Offset int32
}

// =============================================================================
// Analytics Types
// =============================================================================

// UserScanStats represents scan statistics for a user
type UserScanStats struct {
	TotalScans      int64 `json:"total_scans"`
	CompletedScans  int64 `json:"completed_scans"`
	FailedScans     int64 `json:"failed_scans"`
	RunningScans    int64 `json:"running_scans"`
	ScansLast30Days int64 `json:"scans_last_30_days"`
}

// UserFindingStats represents finding statistics for a user
type UserFindingStats struct {
	TotalFindings      int64 `json:"total_findings"`
	CriticalCount      int64 `json:"critical_count"`
	HighCount          int64 `json:"high_count"`
	MediumCount        int64 `json:"medium_count"`
	LowCount           int64 `json:"low_count"`
	InformationalCount int64 `json:"informational_count"`
}

// SeverityCount represents finding count by severity
type SeverityCount struct {
	Severity string `json:"severity"`
	Count    int64  `json:"count"`
}

// ScanTrend represents scan trend data
type ScanTrend struct {
	Date           string `json:"date"`
	ScanCount      int64  `json:"scan_count"`
	CompletedCount int64  `json:"completed_count"`
	FailedCount    int64  `json:"failed_count"`
}

// CategoryStat represents finding count by category
type CategoryStat struct {
	Category      string `json:"category"`
	Count         int64  `json:"count"`
	CriticalCount int64  `json:"critical_count"`
	HighCount     int64  `json:"high_count"`
}

// TopTarget represents a frequently scanned target
type TopTarget struct {
	Target        string    `json:"target"`
	ScanCount     int64     `json:"scan_count"`
	LastScannedAt time.Time `json:"last_scanned_at"`
}

// ============================================================================
// Phase 15: Dashboard & History Types
// ============================================================================

// ScanStatistics represents aggregated scan statistics for dashboard
type ScanStatistics struct {
	TotalScans         int64
	CompletedScans     int64
	FailedScans        int64
	ActiveScans        int64
	ScansThisMonth     int64
	AvgDurationSeconds float64
	LastScanAt         *time.Time
}

// FindingSeverityStats represents findings aggregated by severity for dashboard
type FindingSeverityStats struct {
	Critical      int64
	High          int64
	Medium        int64
	Low           int64
	Informational int64
}

// ScanActivity represents a single scan activity entry
type ScanActivity struct {
	ID            uuid.UUID
	Target        string
	Status        string
	FindingsCount int64
	RiskScore     float64
	StartedAt     time.Time
	CompletedAt   *time.Time
}

// VulnerabilityTrend represents daily vulnerability counts for trends
type VulnerabilityTrend struct {
	Date     string
	Critical int64
	High     int64
	Medium   int64
	Low      int64
	Info     int64
}

// TargetStats represents statistics for a target
type TargetStats struct {
	Target         string
	ScanCount      int64
	LastScannedAt  time.Time
	LastScanID     uuid.UUID
	LastScanStatus string
	AvgRiskScore   float64
	TotalFindings  int64
}

// HistoryFilter represents filter parameters for scan history
type HistoryFilter struct {
	UserID    uuid.UUID
	Status    string
	Target    string
	StartDate *time.Time
	EndDate   *time.Time
	Limit     int32
	Offset    int32
	SortBy    string
	SortOrder string
}

// ScanJobWithStats extends ScanJob with computed statistics
type ScanJobWithStats struct {
	ScanJob
	TotalFindings int64
}

// FindingForDiff represents a finding for diff comparison
type FindingForDiff struct {
	ID          uuid.UUID
	Module      string
	Category    string
	Severity    string
	Title       string
	Description string
	CVSSScore   float64
	Remediation string
}

// =============================================================================
// Type Conversions for pgx
// =============================================================================

// Scan implements pgtype.Scanner for Numeric
func (f *Finding) ScanCVSS(src interface{}) error {
	if src == nil {
		f.CVSSScore = 0
		return nil
	}
	var num pgtype.Numeric
	if err := num.Scan(src); err != nil {
		return err
	}
	// Convert numeric to float64 using Int and Exp
	if num.NaN || num.InfinityModifier != 0 {
		f.CVSSScore = 0
		return nil
	}
	// Convert to float64: value = Int * 10^(-Exp)
	floatVal := float64(num.Int.Int64())
	for i := 0; i < int(num.Exp); i++ {
		floatVal *= 10
	}
	for i := 0; i < int(-num.Exp); i++ {
		floatVal /= 10
	}
	f.CVSSScore = floatVal
	return nil
}

// =============================================================================
// DB Methods Implementation (would normally be generated by sqlc)
// These are stub implementations for compilation
// =============================================================================

// CreateScanJob creates a new scan job
func (d *DB) CreateScanJob(ctx context.Context, params CreateScanJobParams) (*ScanJob, error) {
	query := `
		INSERT INTO scan_jobs (user_id, target, target_type, scope, status, auth_confirmed, auth_confirmed_ip, custom_headers, finding_counts)
		VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
		RETURNING id, user_id, target, target_type, scope, status, auth_confirmed, auth_confirmed_ip, auth_confirmed_at, custom_headers, started_at, completed_at, risk_score, finding_counts, created_at
	`

	row := d.pool.QueryRow(ctx, query,
		params.UserID, params.Target, params.TargetType, params.Scope, params.Status,
		params.AuthConfirmed, params.AuthConfirmedIP, params.CustomHeaders, params.FindingCounts)

	var sj ScanJob
	err := row.Scan(
		&sj.ID, &sj.UserID, &sj.Target, &sj.TargetType, &sj.Scope, &sj.Status,
		&sj.AuthConfirmed, &sj.AuthConfirmedIP, &sj.AuthConfirmedAt, &sj.CustomHeaders,
		&sj.StartedAt, &sj.CompletedAt, &sj.RiskScore, &sj.FindingCounts, &sj.CreatedAt,
	)
	return &sj, err
}

// GetScanJobByID retrieves a scan job by ID
func (d *DB) GetScanJobByID(ctx context.Context, id uuid.UUID) (*ScanJob, error) {
	query := `
		SELECT id, user_id, target, target_type, scope, status, auth_confirmed, auth_confirmed_ip, auth_confirmed_at, custom_headers, started_at, completed_at, risk_score, finding_counts, created_at
		FROM scan_jobs
		WHERE id = $1
	`

	row := d.pool.QueryRow(ctx, query, id)

	var sj ScanJob
	err := row.Scan(
		&sj.ID, &sj.UserID, &sj.Target, &sj.TargetType, &sj.Scope, &sj.Status,
		&sj.AuthConfirmed, &sj.AuthConfirmedIP, &sj.AuthConfirmedAt, &sj.CustomHeaders,
		&sj.StartedAt, &sj.CompletedAt, &sj.RiskScore, &sj.FindingCounts, &sj.CreatedAt,
	)
	if err != nil {
		return nil, err
	}
	return &sj, nil
}

// ListScanJobsByUser lists scan jobs for a user with pagination
func (d *DB) ListScanJobsByUser(ctx context.Context, params ListScanJobsParams) ([]ScanJob, error) {
	query := `
		SELECT id, user_id, target, target_type, scope, status, auth_confirmed, auth_confirmed_ip, auth_confirmed_at, custom_headers, started_at, completed_at, risk_score, finding_counts, created_at
		FROM scan_jobs
		WHERE user_id = $1
		ORDER BY created_at DESC
		LIMIT $2 OFFSET $3
	`

	rows, err := d.pool.Query(ctx, query, params.UserID, params.Limit, params.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var jobs []ScanJob
	for rows.Next() {
		var sj ScanJob
		err := rows.Scan(
			&sj.ID, &sj.UserID, &sj.Target, &sj.TargetType, &sj.Scope, &sj.Status,
			&sj.AuthConfirmed, &sj.AuthConfirmedIP, &sj.AuthConfirmedAt, &sj.CustomHeaders,
			&sj.StartedAt, &sj.CompletedAt, &sj.RiskScore, &sj.FindingCounts, &sj.CreatedAt,
		)
		if err != nil {
			continue
		}
		jobs = append(jobs, sj)
	}
	return jobs, rows.Err()
}

// ListScanJobsByUserAndStatus lists scan jobs filtered by status
func (d *DB) ListScanJobsByUserAndStatus(ctx context.Context, params ListScanJobsByStatusParams) ([]ScanJob, error) {
	query := `
		SELECT id, user_id, target, target_type, scope, status, auth_confirmed, auth_confirmed_ip, auth_confirmed_at, custom_headers, started_at, completed_at, risk_score, finding_counts, created_at
		FROM scan_jobs
		WHERE user_id = $1 AND status = $2
		ORDER BY created_at DESC
		LIMIT $3 OFFSET $4
	`

	rows, err := d.pool.Query(ctx, query, params.UserID, params.Status, params.Limit, params.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var jobs []ScanJob
	for rows.Next() {
		var sj ScanJob
		err := rows.Scan(
			&sj.ID, &sj.UserID, &sj.Target, &sj.TargetType, &sj.Scope, &sj.Status,
			&sj.AuthConfirmed, &sj.AuthConfirmedIP, &sj.AuthConfirmedAt, &sj.CustomHeaders,
			&sj.StartedAt, &sj.CompletedAt, &sj.RiskScore, &sj.FindingCounts, &sj.CreatedAt,
		)
		if err != nil {
			continue
		}
		jobs = append(jobs, sj)
	}
	return jobs, rows.Err()
}

// CountScanJobsByUser counts total scans for a user
func (d *DB) CountScanJobsByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	query := `SELECT COUNT(*) FROM scan_jobs WHERE user_id = $1`
	var count int64
	err := d.pool.QueryRow(ctx, query, userID).Scan(&count)
	return count, err
}

// CountActiveScansByUser counts active (running or pending) scans for a user
func (d *DB) CountActiveScansByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	query := `SELECT COUNT(*) FROM scan_jobs WHERE user_id = $1 AND status IN ('pending', 'queued', 'running')`
	var count int64
	err := d.pool.QueryRow(ctx, query, userID).Scan(&count)
	return count, err
}

// UpdateScanJobStatus updates the status of a scan job
func (d *DB) UpdateScanJobStatus(ctx context.Context, params UpdateScanJobStatusParams) (*ScanJob, error) {
	query := `
		UPDATE scan_jobs
		SET status = $2, updated_at = NOW()
		WHERE id = $1
		RETURNING id, user_id, target, target_type, scope, status, auth_confirmed, auth_confirmed_ip, auth_confirmed_at, custom_headers, started_at, completed_at, risk_score, finding_counts, created_at
	`

	row := d.pool.QueryRow(ctx, query, params.ID, params.Status)

	var sj ScanJob
	err := row.Scan(
		&sj.ID, &sj.UserID, &sj.Target, &sj.TargetType, &sj.Scope, &sj.Status,
		&sj.AuthConfirmed, &sj.AuthConfirmedIP, &sj.AuthConfirmedAt, &sj.CustomHeaders,
		&sj.StartedAt, &sj.CompletedAt, &sj.RiskScore, &sj.FindingCounts, &sj.CreatedAt,
	)
	return &sj, err
}

// UpdateScanJobStarted marks a scan as started
func (d *DB) UpdateScanJobStarted(ctx context.Context, id uuid.UUID) (*ScanJob, error) {
	query := `
		UPDATE scan_jobs
		SET status = 'running', started_at = NOW(), updated_at = NOW()
		WHERE id = $1
		RETURNING id, user_id, target, target_type, scope, status, auth_confirmed, auth_confirmed_ip, auth_confirmed_at, custom_headers, started_at, completed_at, risk_score, finding_counts, created_at
	`

	row := d.pool.QueryRow(ctx, query, id)

	var sj ScanJob
	err := row.Scan(
		&sj.ID, &sj.UserID, &sj.Target, &sj.TargetType, &sj.Scope, &sj.Status,
		&sj.AuthConfirmed, &sj.AuthConfirmedIP, &sj.AuthConfirmedAt, &sj.CustomHeaders,
		&sj.StartedAt, &sj.CompletedAt, &sj.RiskScore, &sj.FindingCounts, &sj.CreatedAt,
	)
	return &sj, err
}

// UpdateScanJobCompleted marks a scan as completed
func (d *DB) UpdateScanJobCompleted(ctx context.Context, params UpdateScanJobCompletedParams) (*ScanJob, error) {
	query := `
		UPDATE scan_jobs
		SET status = 'completed', completed_at = NOW(), risk_score = $2, finding_counts = $3, updated_at = NOW()
		WHERE id = $1
		RETURNING id, user_id, target, target_type, scope, status, auth_confirmed, auth_confirmed_ip, auth_confirmed_at, custom_headers, started_at, completed_at, risk_score, finding_counts, created_at
	`

	row := d.pool.QueryRow(ctx, query, params.ID, params.RiskScore, params.FindingCounts)

	var sj ScanJob
	err := row.Scan(
		&sj.ID, &sj.UserID, &sj.Target, &sj.TargetType, &sj.Scope, &sj.Status,
		&sj.AuthConfirmed, &sj.AuthConfirmedIP, &sj.AuthConfirmedAt, &sj.CustomHeaders,
		&sj.StartedAt, &sj.CompletedAt, &sj.RiskScore, &sj.FindingCounts, &sj.CreatedAt,
	)
	return &sj, err
}

// UpdateScanJobFailed marks a scan as failed
func (d *DB) UpdateScanJobFailed(ctx context.Context, id uuid.UUID) (*ScanJob, error) {
	query := `
		UPDATE scan_jobs
		SET status = 'failed', completed_at = NOW(), updated_at = NOW()
		WHERE id = $1
		RETURNING id, user_id, target, target_type, scope, status, auth_confirmed, auth_confirmed_ip, auth_confirmed_at, custom_headers, started_at, completed_at, risk_score, finding_counts, created_at
	`

	row := d.pool.QueryRow(ctx, query, id)

	var sj ScanJob
	err := row.Scan(
		&sj.ID, &sj.UserID, &sj.Target, &sj.TargetType, &sj.Scope, &sj.Status,
		&sj.AuthConfirmed, &sj.AuthConfirmedIP, &sj.AuthConfirmedAt, &sj.CustomHeaders,
		&sj.StartedAt, &sj.CompletedAt, &sj.RiskScore, &sj.FindingCounts, &sj.CreatedAt,
	)
	return &sj, err
}

// UpdateScanJobAuthConfirmed updates auth confirmation details
func (d *DB) UpdateScanJobAuthConfirmed(ctx context.Context, params UpdateAuthParams) (*ScanJob, error) {
	query := `
		UPDATE scan_jobs
		SET auth_confirmed = true, auth_confirmed_ip = $2, auth_confirmed_at = NOW(), updated_at = NOW()
		WHERE id = $1
		RETURNING id, user_id, target, target_type, scope, status, auth_confirmed, auth_confirmed_ip, auth_confirmed_at, custom_headers, started_at, completed_at, risk_score, finding_counts, created_at
	`

	row := d.pool.QueryRow(ctx, query, params.ID, params.AuthConfirmedIP)

	var sj ScanJob
	err := row.Scan(
		&sj.ID, &sj.UserID, &sj.Target, &sj.TargetType, &sj.Scope, &sj.Status,
		&sj.AuthConfirmed, &sj.AuthConfirmedIP, &sj.AuthConfirmedAt, &sj.CustomHeaders,
		&sj.StartedAt, &sj.CompletedAt, &sj.RiskScore, &sj.FindingCounts, &sj.CreatedAt,
	)
	return &sj, err
}

// GetReportByScanJobID retrieves a report by scan job ID
func (d *DB) GetReportByScanJobID(ctx context.Context, scanJobID uuid.UUID) (*Report, error) {
	query := `
		SELECT id, scan_job_id, pdf_url, json_url, share_token, share_expires_at, executive_summary, remediation_roadmap, created_at
		FROM reports
		WHERE scan_job_id = $1
	`

	row := d.pool.QueryRow(ctx, query, scanJobID)

	var r Report
	err := row.Scan(
		&r.ID, &r.ScanJobID, &r.PDFURL, &r.JSONURL, &r.ShareToken, &r.ShareExpiresAt,
		&r.ExecutiveSummary, &r.RemediationRoadmap, &r.CreatedAt,
	)
	if err != nil {
		return nil, err
	}
	return &r, nil
}

// CreateReport creates a new report record
func (d *DB) CreateReport(ctx context.Context, params CreateReportParams) (*Report, error) {
	query := `
		INSERT INTO reports (
			scan_job_id, pdf_url, json_url, share_token, share_expires_at,
			executive_summary, remediation_roadmap, created_at
		) VALUES (
			$1, $2, $3, $4, $5,
			$6, $7, NOW()
		)
		RETURNING id, scan_job_id, pdf_url, json_url, share_token, share_expires_at, executive_summary, remediation_roadmap, created_at
	`

	row := d.pool.QueryRow(ctx, query,
		params.ScanJobID, params.PDFURL, params.JSONURL, params.ShareToken, params.ShareExpiresAt,
		params.ExecutiveSummary, params.RemediationRoadmap)

	var r Report
	err := row.Scan(
		&r.ID, &r.ScanJobID, &r.PDFURL, &r.JSONURL, &r.ShareToken, &r.ShareExpiresAt,
		&r.ExecutiveSummary, &r.RemediationRoadmap, &r.CreatedAt,
	)
	return &r, err
}

// GetReportByID retrieves a report by ID
func (d *DB) GetReportByID(ctx context.Context, id uuid.UUID) (*Report, error) {
	query := `
		SELECT id, scan_job_id, pdf_url, json_url, share_token, share_expires_at, executive_summary, remediation_roadmap, created_at
		FROM reports
		WHERE id = $1
	`

	row := d.pool.QueryRow(ctx, query, id)

	var r Report
	err := row.Scan(
		&r.ID, &r.ScanJobID, &r.PDFURL, &r.JSONURL, &r.ShareToken, &r.ShareExpiresAt,
		&r.ExecutiveSummary, &r.RemediationRoadmap, &r.CreatedAt,
	)
	if err != nil {
		return nil, err
	}
	return &r, nil
}

// GetReportByShareToken retrieves a report by share token
func (d *DB) GetReportByShareToken(ctx context.Context, shareToken string) (*Report, error) {
	query := `
		SELECT id, scan_job_id, pdf_url, json_url, share_token, share_expires_at, executive_summary, remediation_roadmap, created_at
		FROM reports
		WHERE share_token = $1 AND (share_expires_at IS NULL OR share_expires_at > NOW())
	`

	row := d.pool.QueryRow(ctx, query, shareToken)

	var r Report
	err := row.Scan(
		&r.ID, &r.ScanJobID, &r.PDFURL, &r.JSONURL, &r.ShareToken, &r.ShareExpiresAt,
		&r.ExecutiveSummary, &r.RemediationRoadmap, &r.CreatedAt,
	)
	if err != nil {
		return nil, err
	}
	return &r, nil
}

// ListReportsByUser lists reports for a user with pagination
func (d *DB) ListReportsByUser(ctx context.Context, params ListReportsParams) ([]Report, error) {
	query := `
		SELECT r.id, r.scan_job_id, r.pdf_url, r.json_url, r.share_token, r.share_expires_at, 
			r.executive_summary, r.remediation_roadmap, r.created_at
		FROM reports r
		INNER JOIN scan_jobs sj ON r.scan_job_id = sj.id
		WHERE sj.user_id = $1
		ORDER BY r.created_at DESC
		LIMIT $2 OFFSET $3
	`

	rows, err := d.pool.Query(ctx, query, params.UserID, params.Limit, params.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var reports []Report
	for rows.Next() {
		var r Report
		err := rows.Scan(
			&r.ID, &r.ScanJobID, &r.PDFURL, &r.JSONURL, &r.ShareToken, &r.ShareExpiresAt,
			&r.ExecutiveSummary, &r.RemediationRoadmap, &r.CreatedAt,
		)
		if err != nil {
			continue
		}
		reports = append(reports, r)
	}
	return reports, rows.Err()
}

// UpdateReportShareToken updates the share token for a report
func (d *DB) UpdateReportShareToken(ctx context.Context, params UpdateShareParams) (*Report, error) {
	query := `
		UPDATE reports
		SET share_token = $2, share_expires_at = $3
		WHERE id = $1
		RETURNING id, scan_job_id, pdf_url, json_url, share_token, share_expires_at, executive_summary, remediation_roadmap, created_at
	`

	row := d.pool.QueryRow(ctx, query, params.ID, params.ShareToken, params.ExpiresAt)

	var r Report
	err := row.Scan(
		&r.ID, &r.ScanJobID, &r.PDFURL, &r.JSONURL, &r.ShareToken, &r.ShareExpiresAt,
		&r.ExecutiveSummary, &r.RemediationRoadmap, &r.CreatedAt,
	)
	return &r, err
}

// RevokeReportShare removes the share token from a report
func (d *DB) RevokeReportShare(ctx context.Context, id uuid.UUID) (*Report, error) {
	query := `
		UPDATE reports
		SET share_token = NULL, share_expires_at = NULL
		WHERE id = $1
		RETURNING id, scan_job_id, pdf_url, json_url, share_token, share_expires_at, executive_summary, remediation_roadmap, created_at
	`

	row := d.pool.QueryRow(ctx, query, id)

	var r Report
	err := row.Scan(
		&r.ID, &r.ScanJobID, &r.PDFURL, &r.JSONURL, &r.ShareToken, &r.ShareExpiresAt,
		&r.ExecutiveSummary, &r.RemediationRoadmap, &r.CreatedAt,
	)
	return &r, err
}

// DeleteReport deletes a report
func (d *DB) DeleteReport(ctx context.Context, id uuid.UUID) error {
	query := `DELETE FROM reports WHERE id = $1`
	_, err := d.pool.Exec(ctx, query, id)
	return err
}

// UpdateReportURLs updates the PDF and JSON URLs for a report
func (d *DB) UpdateReportURLs(ctx context.Context, reportID uuid.UUID, pdfURL, jsonURL string) (*Report, error) {
	query := `
		UPDATE reports
		SET pdf_url = $2, json_url = $3
		WHERE id = $1
		RETURNING id, scan_job_id, pdf_url, json_url, share_token, share_expires_at, executive_summary, remediation_roadmap, created_at
	`

	row := d.pool.QueryRow(ctx, query, reportID, pdfURL, jsonURL)

	var r Report
	err := row.Scan(
		&r.ID, &r.ScanJobID, &r.PDFURL, &r.JSONURL, &r.ShareToken, &r.ShareExpiresAt,
		&r.ExecutiveSummary, &r.RemediationRoadmap, &r.CreatedAt,
	)
	return &r, err
}

// ============================================================================
// Phase 15: Dashboard Methods Implementation
// ============================================================================

// GetScanStatistics retrieves aggregated scan statistics for a user
func (d *DB) GetScanStatistics(ctx context.Context, userID uuid.UUID) (*ScanStatistics, error) {
	query := `
		SELECT 
			COUNT(*) as total_scans,
			COUNT(*) FILTER (WHERE status = 'completed') as completed_scans,
			COUNT(*) FILTER (WHERE status = 'failed') as failed_scans,
			COUNT(*) FILTER (WHERE status IN ('pending', 'queued', 'running')) as active_scans,
			COUNT(*) FILTER (WHERE created_at > DATE_TRUNC('month', NOW())) as scans_this_month,
			COALESCE(AVG(EXTRACT(EPOCH FROM (completed_at - started_at))) FILTER (WHERE completed_at IS NOT NULL AND started_at IS NOT NULL), 0) as avg_duration_seconds,
			MAX(created_at) as last_scan_at
		FROM scan_jobs
		WHERE user_id = $1
	`

	var stats ScanStatistics
	var lastScanAt *time.Time

	err := d.pool.QueryRow(ctx, query, userID).Scan(
		&stats.TotalScans,
		&stats.CompletedScans,
		&stats.FailedScans,
		&stats.ActiveScans,
		&stats.ScansThisMonth,
		&stats.AvgDurationSeconds,
		&lastScanAt,
	)
	if err != nil {
		return nil, err
	}

	stats.LastScanAt = lastScanAt
	return &stats, nil
}

// GetFindingsBySeverityStats retrieves finding counts by severity for a user
func (d *DB) GetFindingsBySeverityStats(ctx context.Context, userID uuid.UUID) (*FindingSeverityStats, error) {
	query := `
		SELECT 
			COUNT(*) FILTER (WHERE severity = 'Critical') as critical,
			COUNT(*) FILTER (WHERE severity = 'High') as high,
			COUNT(*) FILTER (WHERE severity = 'Medium') as medium,
			COUNT(*) FILTER (WHERE severity = 'Low') as low,
			COUNT(*) FILTER (WHERE severity = 'Informational') as informational
		FROM findings f
		INNER JOIN scan_jobs sj ON f.scan_job_id = sj.id
		WHERE sj.user_id = $1
	`

	var stats FindingSeverityStats
	err := d.pool.QueryRow(ctx, query, userID).Scan(
		&stats.Critical,
		&stats.High,
		&stats.Medium,
		&stats.Low,
		&stats.Informational,
	)
	if err != nil {
		return nil, err
	}

	return &stats, nil
}

// GetScanActivity retrieves recent scan activity with pagination
func (d *DB) GetScanActivity(ctx context.Context, userID uuid.UUID, limit, offset int32) ([]ScanActivity, int64, error) {
	// Get total count
	var total int64
	countQuery := `SELECT COUNT(*) FROM scan_jobs WHERE user_id = $1`
	if err := d.pool.QueryRow(ctx, countQuery, userID).Scan(&total); err != nil {
		return nil, 0, err
	}

	// Get activities
	query := `
		SELECT 
			sj.id,
			sj.target,
			sj.status,
			COALESCE((SELECT COUNT(*) FROM findings f WHERE f.scan_job_id = sj.id), 0) as findings_count,
			COALESCE(sj.risk_score, 0) / 10.0 as risk_score,
			COALESCE(sj.started_at, sj.created_at) as started_at,
			sj.completed_at
		FROM scan_jobs sj
		WHERE sj.user_id = $1
		ORDER BY sj.created_at DESC
		LIMIT $2 OFFSET $3
	`

	rows, err := d.pool.Query(ctx, query, userID, limit, offset)
	if err != nil {
		return nil, 0, err
	}
	defer rows.Close()

	var activities []ScanActivity
	for rows.Next() {
		var activity ScanActivity
		var completedAt *time.Time
		err := rows.Scan(
			&activity.ID,
			&activity.Target,
			&activity.Status,
			&activity.FindingsCount,
			&activity.RiskScore,
			&activity.StartedAt,
			&completedAt,
		)
		if err != nil {
			continue
		}
		activity.CompletedAt = completedAt
		activities = append(activities, activity)
	}

	return activities, total, rows.Err()
}

// GetVulnerabilityTrends retrieves daily vulnerability counts for trend charts
func (d *DB) GetVulnerabilityTrends(ctx context.Context, userID uuid.UUID, days int, startDate, endDate *time.Time) ([]VulnerabilityTrend, error) {
	// Determine date range
	var start, end time.Time
	if startDate != nil && endDate != nil {
		start = *startDate
		end = *endDate
	} else {
		end = time.Now()
		start = end.AddDate(0, 0, -days)
	}

	query := `
		WITH date_series AS (
			SELECT generate_series($2::date, $3::date, '1 day'::interval)::date as date
		),
		daily_findings AS (
			SELECT 
				DATE(f.created_at) as date,
				COUNT(*) FILTER (WHERE f.severity = 'Critical') as critical,
				COUNT(*) FILTER (WHERE f.severity = 'High') as high,
				COUNT(*) FILTER (WHERE f.severity = 'Medium') as medium,
				COUNT(*) FILTER (WHERE f.severity = 'Low') as low,
				COUNT(*) FILTER (WHERE f.severity = 'Informational') as info
			FROM findings f
			INNER JOIN scan_jobs sj ON f.scan_job_id = sj.id
			WHERE sj.user_id = $1
				AND f.created_at BETWEEN $2 AND $3
			GROUP BY DATE(f.created_at)
		)
		SELECT 
			ds.date::text,
			COALESCE(df.critical, 0) as critical,
			COALESCE(df.high, 0) as high,
			COALESCE(df.medium, 0) as medium,
			COALESCE(df.low, 0) as low,
			COALESCE(df.info, 0) as info
		FROM date_series ds
		LEFT JOIN daily_findings df ON ds.date = df.date
		ORDER BY ds.date ASC
	`

	rows, err := d.pool.Query(ctx, query, userID, start, end)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var trends []VulnerabilityTrend
	for rows.Next() {
		var trend VulnerabilityTrend
		err := rows.Scan(
			&trend.Date,
			&trend.Critical,
			&trend.High,
			&trend.Medium,
			&trend.Low,
			&trend.Info,
		)
		if err != nil {
			continue
		}
		trends = append(trends, trend)
	}

	return trends, rows.Err()
}

// GetMostScannedTargets retrieves the most frequently scanned targets
func (d *DB) GetMostScannedTargets(ctx context.Context, userID uuid.UUID, limit int32) ([]TargetStats, int64, error) {
	// Get total unique targets count
	var total int64
	countQuery := `
		SELECT COUNT(DISTINCT target) 
		FROM scan_jobs 
		WHERE user_id = $1
	`
	if err := d.pool.QueryRow(ctx, countQuery, userID).Scan(&total); err != nil {
		return nil, 0, err
	}

	query := `
		WITH target_stats AS (
			SELECT 
				target,
				COUNT(*) as scan_count,
				MAX(created_at) as last_scanned_at,
				(
					SELECT id FROM scan_jobs 
					WHERE user_id = $1 AND target = sj.target 
					ORDER BY created_at DESC LIMIT 1
				) as last_scan_id,
				(
					SELECT status FROM scan_jobs 
					WHERE user_id = $1 AND target = sj.target 
					ORDER BY created_at DESC LIMIT 1
				) as last_scan_status,
				COALESCE(AVG(risk_score) FILTER (WHERE risk_score > 0), 0) / 10.0 as avg_risk_score
			FROM scan_jobs sj
			WHERE user_id = $1
			GROUP BY target
		)
		SELECT 
			ts.target,
			ts.scan_count,
			ts.last_scanned_at,
			ts.last_scan_id,
			ts.last_scan_status,
			ts.avg_risk_score,
			COALESCE((
				SELECT COUNT(*) 
				FROM findings f 
				WHERE f.scan_job_id = ts.last_scan_id
			), 0) as total_findings
		FROM target_stats ts
		ORDER BY ts.scan_count DESC, ts.last_scanned_at DESC
		LIMIT $2
	`

	rows, err := d.pool.Query(ctx, query, userID, limit)
	if err != nil {
		return nil, 0, err
	}
	defer rows.Close()

	var targets []TargetStats
	for rows.Next() {
		var target TargetStats
		err := rows.Scan(
			&target.Target,
			&target.ScanCount,
			&target.LastScannedAt,
			&target.LastScanID,
			&target.LastScanStatus,
			&target.AvgRiskScore,
			&target.TotalFindings,
		)
		if err != nil {
			continue
		}
		targets = append(targets, target)
	}

	return targets, total, rows.Err()
}

// ============================================================================
// Phase 15: History Methods Implementation
// ============================================================================

// GetScanHistory retrieves filtered scan history
func (d *DB) GetScanHistory(ctx context.Context, filter HistoryFilter) ([]*ScanJobWithStats, int64, error) {
	// Build the base query
	whereClause := "WHERE user_id = $1"
	params := []interface{}{filter.UserID}
	paramIndex := 2

	if filter.Status != "" {
		whereClause += fmt.Sprintf(" AND status = $%d", paramIndex)
		params = append(params, filter.Status)
		paramIndex++
	}

	if filter.Target != "" {
		whereClause += fmt.Sprintf(" AND target ILIKE $%d", paramIndex)
		params = append(params, "%"+filter.Target+"%")
		paramIndex++
	}

	if filter.StartDate != nil {
		whereClause += fmt.Sprintf(" AND created_at >= $%d", paramIndex)
		params = append(params, *filter.StartDate)
		paramIndex++
	}

	if filter.EndDate != nil {
		whereClause += fmt.Sprintf(" AND created_at <= $%d", paramIndex)
		params = append(params, *filter.EndDate)
		paramIndex++
	}

	// Get total count
	countQuery := fmt.Sprintf("SELECT COUNT(*) FROM scan_jobs %s", whereClause)
	var total int64
	if err := d.pool.QueryRow(ctx, countQuery, params...).Scan(&total); err != nil {
		return nil, 0, err
	}

	// Determine sort order
	sortBy := "created_at"
	if filter.SortBy != "" {
		sortBy = filter.SortBy
	}
	sortOrder := "DESC"
	if filter.SortOrder == "asc" {
		sortOrder = "ASC"
	}

	// Build main query
	query := fmt.Sprintf(`
		SELECT 
			id, user_id, target, target_type, scope, status, auth_confirmed,
			auth_confirmed_ip, auth_confirmed_at, custom_headers, started_at,
			completed_at, risk_score, finding_counts, created_at,
			COALESCE((SELECT COUNT(*) FROM findings f WHERE f.scan_job_id = sj.id), 0) as total_findings
		FROM scan_jobs sj
		%s
		ORDER BY %s %s
		LIMIT $%d OFFSET $%d
	`, whereClause, sortBy, sortOrder, paramIndex, paramIndex+1)

	params = append(params, filter.Limit, filter.Offset)

	rows, err := d.pool.Query(ctx, query, params...)
	if err != nil {
		return nil, 0, err
	}
	defer rows.Close()

	var jobs []*ScanJobWithStats
	for rows.Next() {
		var job ScanJobWithStats
		err := rows.Scan(
			&job.ID, &job.UserID, &job.Target, &job.TargetType, &job.Scope, &job.Status,
			&job.AuthConfirmed, &job.AuthConfirmedIP, &job.AuthConfirmedAt, &job.CustomHeaders,
			&job.StartedAt, &job.CompletedAt, &job.RiskScore, &job.FindingCounts, &job.CreatedAt,
			&job.TotalFindings,
		)
		if err != nil {
			continue
		}
		jobs = append(jobs, &job)
	}

	return jobs, total, rows.Err()
}

// GetTargetScanHistory retrieves all scans for a specific target
func (d *DB) GetTargetScanHistory(ctx context.Context, userID uuid.UUID, target string, limit, offset int32) ([]*ScanJobWithStats, int64, error) {
	// Get total count
	var total int64
	countQuery := `
		SELECT COUNT(*) FROM scan_jobs 
		WHERE user_id = $1 AND target = $2
	`
	if err := d.pool.QueryRow(ctx, countQuery, userID, target).Scan(&total); err != nil {
		return nil, 0, err
	}

	query := `
		SELECT 
			sj.id, sj.user_id, sj.target, sj.target_type, sj.scope, sj.status,
			sj.auth_confirmed, sj.auth_confirmed_ip, sj.auth_confirmed_at,
			sj.custom_headers, sj.started_at, sj.completed_at, sj.risk_score,
			sj.finding_counts, sj.created_at,
			COALESCE((SELECT COUNT(*) FROM findings f WHERE f.scan_job_id = sj.id), 0) as total_findings
		FROM scan_jobs sj
		WHERE sj.user_id = $1 AND sj.target = $2
		ORDER BY sj.created_at DESC
		LIMIT $3 OFFSET $4
	`

	rows, err := d.pool.Query(ctx, query, userID, target, limit, offset)
	if err != nil {
		return nil, 0, err
	}
	defer rows.Close()

	var jobs []*ScanJobWithStats
	for rows.Next() {
		var job ScanJobWithStats
		err := rows.Scan(
			&job.ID, &job.UserID, &job.Target, &job.TargetType, &job.Scope, &job.Status,
			&job.AuthConfirmed, &job.AuthConfirmedIP, &job.AuthConfirmedAt, &job.CustomHeaders,
			&job.StartedAt, &job.CompletedAt, &job.RiskScore, &job.FindingCounts, &job.CreatedAt,
			&job.TotalFindings,
		)
		if err != nil {
			continue
		}
		jobs = append(jobs, &job)
	}

	return jobs, total, rows.Err()
}

// ============================================================================
// Phase 15: Diff Methods Implementation
// ============================================================================

// GetScanFindingsForDiff retrieves findings for diff comparison
func (d *DB) GetScanFindingsForDiff(ctx context.Context, scanJobID uuid.UUID) ([]*FindingForDiff, error) {
	query := `
		SELECT 
			id, module, category, severity, title, description,
			COALESCE(cvss_score, 0) as cvss_score, COALESCE(remediation, '') as remediation
		FROM findings
		WHERE scan_job_id = $1
		ORDER BY 
			CASE severity
				WHEN 'Critical' THEN 1
				WHEN 'High' THEN 2
				WHEN 'Medium' THEN 3
				WHEN 'Low' THEN 4
				WHEN 'Informational' THEN 5
			END,
			created_at DESC
	`

	rows, err := d.pool.Query(ctx, query, scanJobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var findings []*FindingForDiff
	for rows.Next() {
		var f FindingForDiff
		err := rows.Scan(
			&f.ID, &f.Module, &f.Category, &f.Severity, &f.Title,
			&f.Description, &f.CVSSScore, &f.Remediation,
		)
		if err != nil {
			continue
		}
		findings = append(findings, &f)
	}

	return findings, rows.Err()
}

// ============================================================================
// Phase 16: Billing Types
// ============================================================================

// Subscription represents a user subscription
type Subscription struct {
	ID                   uuid.UUID  `json:"id" db:"id"`
	UserID               uuid.UUID  `json:"user_id" db:"user_id"`
	StripeCustomerID     string     `json:"stripe_customer_id,omitempty" db:"stripe_customer_id"`
	StripeSubscriptionID string     `json:"stripe_subscription_id,omitempty" db:"stripe_subscription_id"`
	Tier                 string     `json:"tier" db:"tier"`
	Status               string     `json:"status" db:"status"`
	CurrentPeriodStart   *time.Time `json:"current_period_start,omitempty" db:"current_period_start"`
	CurrentPeriodEnd     *time.Time `json:"current_period_end,omitempty" db:"current_period_end"`
	CancelAtPeriodEnd    bool       `json:"cancel_at_period_end" db:"cancel_at_period_end"`
	CanceledAt           *time.Time `json:"canceled_at,omitempty" db:"canceled_at"`
	CreatedAt            time.Time  `json:"created_at" db:"created_at"`
	UpdatedAt            time.Time  `json:"updated_at" db:"updated_at"`
}

// BillingEvent represents a billing event for audit
type BillingEvent struct {
	ID            uuid.UUID       `json:"id" db:"id"`
	UserID        uuid.UUID       `json:"user_id" db:"user_id"`
	StripeEventID string          `json:"stripe_event_id,omitempty" db:"stripe_event_id"`
	EventType     string          `json:"event_type" db:"event_type"`
	EventData     json.RawMessage `json:"event_data" db:"event_data"`
	ProcessedAt   time.Time       `json:"processed_at" db:"processed_at"`
	CreatedAt     time.Time       `json:"created_at" db:"created_at"`
}

// DailyScanUsage represents daily scan usage for a user
type DailyScanUsage struct {
	ID        uuid.UUID `json:"id" db:"id"`
	UserID    uuid.UUID `json:"user_id" db:"user_id"`
	ScanDate  time.Time `json:"scan_date" db:"scan_date"`
	ScanCount int       `json:"scan_count" db:"scan_count"`
	CreatedAt time.Time `json:"created_at" db:"created_at"`
	UpdatedAt time.Time `json:"updated_at" db:"updated_at"`
}

// CreateSubscriptionParams parameters for creating a subscription
type CreateSubscriptionParams struct {
	UserID               uuid.UUID
	StripeCustomerID     string
	StripeSubscriptionID string
	Tier                 string
	Status               string
	CurrentPeriodStart   *time.Time
	CurrentPeriodEnd     *time.Time
}

// UpdateSubscriptionParams parameters for updating a subscription
type UpdateSubscriptionParams struct {
	ID                 uuid.UUID
	Status             string
	CurrentPeriodStart *time.Time
	CurrentPeriodEnd   *time.Time
	CancelAtPeriodEnd  bool
	CanceledAt         *time.Time
}

// ============================================================================
// Phase 16: Billing Methods
// ============================================================================

// GetUserSubscription retrieves the subscription for a user
func (d *DB) GetUserSubscription(ctx context.Context, userID uuid.UUID) (*Subscription, error) {
	query := `
		SELECT id, user_id, stripe_customer_id, stripe_subscription_id, tier, status,
		       current_period_start, current_period_end, cancel_at_period_end, canceled_at,
		       created_at, updated_at
		FROM subscriptions
		WHERE user_id = $1
		ORDER BY created_at DESC
		LIMIT 1
	`

	row := d.pool.QueryRow(ctx, query, userID)

	var sub Subscription
	err := row.Scan(
		&sub.ID, &sub.UserID, &sub.StripeCustomerID, &sub.StripeSubscriptionID,
		&sub.Tier, &sub.Status, &sub.CurrentPeriodStart, &sub.CurrentPeriodEnd,
		&sub.CancelAtPeriodEnd, &sub.CanceledAt, &sub.CreatedAt, &sub.UpdatedAt,
	)
	if err != nil {
		return nil, err
	}
	return &sub, nil
}

// GetSubscriptionByStripeID retrieves a subscription by Stripe subscription ID
func (d *DB) GetSubscriptionByStripeID(ctx context.Context, stripeSubscriptionID string) (*Subscription, error) {
	query := `
		SELECT id, user_id, stripe_customer_id, stripe_subscription_id, tier, status,
		       current_period_start, current_period_end, cancel_at_period_end, canceled_at,
		       created_at, updated_at
		FROM subscriptions
		WHERE stripe_subscription_id = $1
	`

	row := d.pool.QueryRow(ctx, query, stripeSubscriptionID)

	var sub Subscription
	err := row.Scan(
		&sub.ID, &sub.UserID, &sub.StripeCustomerID, &sub.StripeSubscriptionID,
		&sub.Tier, &sub.Status, &sub.CurrentPeriodStart, &sub.CurrentPeriodEnd,
		&sub.CancelAtPeriodEnd, &sub.CanceledAt, &sub.CreatedAt, &sub.UpdatedAt,
	)
	if err != nil {
		return nil, err
	}
	return &sub, nil
}

// CreateSubscription creates a new subscription
func (d *DB) CreateSubscription(ctx context.Context, params CreateSubscriptionParams) (*Subscription, error) {
	query := `
		INSERT INTO subscriptions (
			user_id, stripe_customer_id, stripe_subscription_id, tier, status,
			current_period_start, current_period_end
		)
		VALUES ($1, $2, $3, $4, $5, $6, $7)
		ON CONFLICT (stripe_subscription_id) DO UPDATE SET
			status = EXCLUDED.status,
			current_period_start = EXCLUDED.current_period_start,
			current_period_end = EXCLUDED.current_period_end,
			updated_at = NOW()
		RETURNING id, user_id, stripe_customer_id, stripe_subscription_id, tier, status,
		          current_period_start, current_period_end, cancel_at_period_end, canceled_at,
		          created_at, updated_at
	`

	row := d.pool.QueryRow(ctx, query,
		params.UserID, params.StripeCustomerID, params.StripeSubscriptionID,
		params.Tier, params.Status, params.CurrentPeriodStart, params.CurrentPeriodEnd)

	var sub Subscription
	err := row.Scan(
		&sub.ID, &sub.UserID, &sub.StripeCustomerID, &sub.StripeSubscriptionID,
		&sub.Tier, &sub.Status, &sub.CurrentPeriodStart, &sub.CurrentPeriodEnd,
		&sub.CancelAtPeriodEnd, &sub.CanceledAt, &sub.CreatedAt, &sub.UpdatedAt,
	)
	return &sub, err
}

// UpdateSubscription updates a subscription
func (d *DB) UpdateSubscription(ctx context.Context, params UpdateSubscriptionParams) (*Subscription, error) {
	query := `
		UPDATE subscriptions
		SET status = $2,
		    current_period_start = $3,
		    current_period_end = $4,
		    cancel_at_period_end = $5,
		    canceled_at = $6,
		    updated_at = NOW()
		WHERE id = $1
		RETURNING id, user_id, stripe_customer_id, stripe_subscription_id, tier, status,
		          current_period_start, current_period_end, cancel_at_period_end, canceled_at,
		          created_at, updated_at
	`

	row := d.pool.QueryRow(ctx, query,
		params.ID, params.Status, params.CurrentPeriodStart,
		params.CurrentPeriodEnd, params.CancelAtPeriodEnd, params.CanceledAt)

	var sub Subscription
	err := row.Scan(
		&sub.ID, &sub.UserID, &sub.StripeCustomerID, &sub.StripeSubscriptionID,
		&sub.Tier, &sub.Status, &sub.CurrentPeriodStart, &sub.CurrentPeriodEnd,
		&sub.CancelAtPeriodEnd, &sub.CanceledAt, &sub.CreatedAt, &sub.UpdatedAt,
	)
	return &sub, err
}

// CancelSubscription marks a subscription as canceled
func (d *DB) CancelSubscription(ctx context.Context, id uuid.UUID) (*Subscription, error) {
	query := `
		UPDATE subscriptions
		SET status = 'canceled',
		    canceled_at = NOW(),
		    updated_at = NOW()
		WHERE id = $1
		RETURNING id, user_id, stripe_customer_id, stripe_subscription_id, tier, status,
		          current_period_start, current_period_end, cancel_at_period_end, canceled_at,
		          created_at, updated_at
	`

	row := d.pool.QueryRow(ctx, query, id)

	var sub Subscription
	err := row.Scan(
		&sub.ID, &sub.UserID, &sub.StripeCustomerID, &sub.StripeSubscriptionID,
		&sub.Tier, &sub.Status, &sub.CurrentPeriodStart, &sub.CurrentPeriodEnd,
		&sub.CancelAtPeriodEnd, &sub.CanceledAt, &sub.CreatedAt, &sub.UpdatedAt,
	)
	return &sub, err
}

// CreateBillingEvent creates a billing event log entry
func (d *DB) CreateBillingEvent(ctx context.Context, event BillingEvent) error {
	query := `
		INSERT INTO billing_events (user_id, stripe_event_id, event_type, event_data)
		VALUES ($1, $2, $3, $4)
	`

	_, err := d.pool.Exec(ctx, query,
		event.UserID, event.StripeEventID, event.EventType, event.EventData)
	return err
}

// GetDailyScanUsage retrieves the scan count for a user on a specific date
func (d *DB) GetDailyScanUsage(ctx context.Context, userID uuid.UUID, date time.Time) (int, error) {
	query := `
		SELECT scan_count
		FROM daily_scan_usage
		WHERE user_id = $1 AND scan_date = $2
	`

	var count int
	err := d.pool.QueryRow(ctx, query, userID, date).Scan(&count)
	if err != nil {
		// No record means 0 scans
		return 0, nil
	}
	return count, nil
}

// IncrementDailyScanCount increments the scan count for a user
func (d *DB) IncrementDailyScanCount(ctx context.Context, userID uuid.UUID) (int, error) {
	query := `
		INSERT INTO daily_scan_usage (user_id, scan_date, scan_count)
		VALUES ($1, CURRENT_DATE, 1)
		ON CONFLICT (user_id, scan_date)
		DO UPDATE SET
			scan_count = daily_scan_usage.scan_count + 1,
			updated_at = NOW()
		RETURNING scan_count
	`

	var count int
	err := d.pool.QueryRow(ctx, query, userID).Scan(&count)
	return count, err
}

// CheckScanLimit checks if a user has exceeded their daily scan limit
func (d *DB) CheckScanLimit(ctx context.Context, userID uuid.UUID, tier string) (bool, error) {
	query := `
		SELECT check_scan_limit($1, $2)
	`

	var allowed bool
	err := d.pool.QueryRow(ctx, query, userID, tier).Scan(&allowed)
	return allowed, err
}

// UpdateUserTier updates a user's tier
func (d *DB) UpdateUserTier(ctx context.Context, params UpdateUserTierParams) (*User, error) {
	query := `
		UPDATE users
		SET tier = $2, updated_at = NOW()
		WHERE id = $1
		RETURNING id, clerk_user_id, tier, api_key, created_at, updated_at
	`

	row := d.pool.QueryRow(ctx, query, params.ID, params.Tier)

	var user User
	err := row.Scan(
		&user.ID, &user.ClerkUserID, &user.Tier, &user.APIKey,
		&user.CreatedAt, &user.UpdatedAt,
	)
	return &user, err
}

// GetUserByID retrieves a user by ID
func (d *DB) GetUserByID(ctx context.Context, id uuid.UUID) (*User, error) {
	query := `
		SELECT id, clerk_user_id, tier, api_key, created_at, updated_at
		FROM users
		WHERE id = $1
	`

	row := d.pool.QueryRow(ctx, query, id)

	var user User
	err := row.Scan(
		&user.ID, &user.ClerkUserID, &user.Tier, &user.APIKey,
		&user.CreatedAt, &user.UpdatedAt,
	)
	if err != nil {
		return nil, err
	}
	return &user, nil
}
